//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcustomer()
        {
            this.moviebookings = new HashSet<moviebooking>();
        }
    
        public int cid { get; set; }
        public string cname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moviebooking> moviebookings { get; set; }
    }
}
