//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmovie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmovie()
        {
            this.tblscreens = new HashSet<tblscreen>();
        }
    
        public int movieid { get; set; }
        public string moviename { get; set; }
        public Nullable<System.DateTime> YearOfMovie { get; set; }
        public Nullable<System.DateTime> releasedate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblscreen> tblscreens { get; set; }
    }
}
