//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviebooking
    {
        public int bookingid { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> cid { get; set; }
        public int noofseats { get; set; }
        public int totalamount { get; set; }
    
        public virtual tblcustomer tblcustomer { get; set; }
        public virtual tblscreen tblscreen { get; set; }
    }
}
