//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblscreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblscreen()
        {
            this.moviebookings = new HashSet<moviebooking>();
        }
    
        public int sid { get; set; }
        public Nullable<int> theatreid { get; set; }
        public Nullable<int> movieid { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> Noofseats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moviebooking> moviebookings { get; set; }
        public virtual tblmovie tblmovie { get; set; }
        public virtual tbltheatre tbltheatre { get; set; }
    }
}
